version: "3.7"
services:
  app:
    image: nginx
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://app
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: google
      OAUTH2_PROXY_PROVIDER: google
      OAUTH2_PROXY_CLIENT_ID: 945751821525-7qiprne3se8acburqe9nf1b38sfr0n7k.apps.googleusercontent.com
      OAUTH2_PROXY_CLIENT_SECRET: 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
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:4180/oauth2/callback
      OAUTH2_PROXY_COOKIE_SECRET: CpDAqXCEQJBQ1uCXmc40BLjgOHuycaewpnSkj7mm8dQ

    ports:
      - 4180:4180
    
    
      
