version: "3.7"
services:
  app:
    image: nginx
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    depends_on:
     - postgres
    restart: always
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://app
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: keycloak
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_CLIENT_ID: my-client
      OAUTH2_PROXY_CLIENT_SECRET: f20af500-9a3e-44e1-b552-498379e21c8b
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:4180/oauth2/callback
      OAUTH2_PROXY_COOKIE_SECRET: CpDAqXCEQJBQ1uCXmc40BLjgOHuycaewpnSkj7mm8dQ
      OAUTH2_PROXY_LOGIN_URL: http://39f8-167-0-182-18.ngrok.io/auth/realms/test/protocol/openid-connect/auth
      OAUTH2_PROXY_REDEEM_URL: http://39f8-167-0-182-18.ngrok.io/auth/realms/test/protocol/openid-connect/token
      OAUTH2_PROXY_PROFILE_URL: http://39f8-167-0-182-18.ngrok.io/auth/realms/test/protocol/openid-connect/userinfo"
      OAUTH2_PROXY_ISSUER_URL: http://39f8-167-0-182-18.ngrok.io/auth/realms/test
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://39f8-167-0-182-18.ngrok.io/auth/realms/test


    ports:
      - 4180:4180



  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    image: jboss/keycloak:13.0.0
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak


networks:
  local-keycloak:
